name = "hex-number-field"
defaultTargets = ["HexNumberField"]

leanOptions = [
  { name = "doc.verso", value = true },
  { name = "doc.verso.suggestions", value = false },
]

[[require]]
name = "HexRoots"
git = "https://github.com/leanprover/hex-roots.git"
rev = "1cbee8873adc3c6587a00aa288f675be6d105818"

[[require]]
name = "HexRowReduce"
git = "https://github.com/leanprover/hex-row-reduce.git"
rev = "7550b5334bea67cba65c9a96a87d24557090784f"

[[require]]
name = "HexResultant"
git = "https://github.com/leanprover/hex-resultant.git"
rev = "449bea55585ac61e8a8cbd6ef5b0c8625283beff"

[[require]]
name = "HexBerlekampZassenhaus"
git = "https://github.com/leanprover/hex-berlekamp-zassenhaus.git"
rev = "5b59d167f5bac139c2bf6f7a654476881314ff23"

[[require]]
name = "batteries"
git = "https://github.com/leanprover-community/batteries"
rev = "main"

[[lean_lib]]
name = "HexNumberField"
